apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  project: infrastructure
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
  source:
    path: infrastructure-argocd/auth
    repoURL: 'https://github.com/tkagn/ocp4gitops-public'
