apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odf-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: "https://kubernetes.default.svc"
  project: infrastructure
  source:
    helm:
      releaseName: odf-operator
    chart: odf-operator
    repoURL: 'https://tkagn.github.io/helmcharts/'
    targetRevision: 0.2.0
  syncPolicy:
    automated:
      prune: false
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

