apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: oadp-operator
  namespace: openshift-adp
spec:
  channel: stable-1.0
  installPlanApproval: Automatic
  name: oadp-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
