apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./ocpgitops-subscription.yaml     # Use eith openshift-gitops or argocd. Not both
  - ./openshift-gitops-cluster.yaml
  - ./project-infrastructure.yaml
  - ./application-infrastructure.yaml
