apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./ocpgitops-subscription.yaml
  - ./argocd-cluster.yaml
  - ./project-infrastructure
  - ./application-infrastructure.yaml