apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: infrastructure

resources:
  - oauth-application.yaml
  - application-machinesets.yaml
#  - ocs-application.yaml
#  - ocs-application-helmchart.yaml 
#  - odf-application.yaml
#  - odf-application-helmchart.yaml
#  - oadp-application.yaml
#  - crunchy-postgres-application.yaml
#  - lso-application.yaml

