apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: "https://kubernetes.default.svc"
  project: infrastructure
  syncPolicy: {}
  source:
    path: infrastructure/auth
    repoURL: 'https://github.com/tkagn/ocp4gitops-public'
