apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "ArgoCD project for gitops"
    openshift.io/display-name: "ArgoCD"
  labels:
    app.kubernetes.io/instance: argocd
    openshift.io/cluster-monitoring: "true"
  name: argocd
spec: {}

 
