kind: Secret
apiVersion: v1
metadata:
  name: cloud-credentials
  namespace: openshift-adp
data:
  cloud: >-
    W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkPQphd3Nfc2VjcmV0X2FjY2Vzc19rZXk9CgpbdGVuYW50MS1ic2xdCmF3c19hY2Nlc3Nfa2V5X2lkPTBjSWNJWDVManNXVjBJZjNTWjVMCmF3c19zZWNyZXRfYWNjZXNzX2tleT1xWmU4TzA4RE16dlR2Y0xySHd6MjZ3YkNZL21lQzNXSmhWcVhSa28zCgoKCg==
type: Opaque


