apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: cluster-24f2-xltdt-storage-us-east-2b
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-24f2-xltdt
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-24f2-xltdt
      machine.openshift.io/cluster-api-machineset: cluster-24f2-xltdt-storage-us-east-2b
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-24f2-xltdt
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: cluster-24f2-xltdt-storage-us-east-2b
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
          cluster.ocs.openshift.io/openshift-storage: ''
      taints:
        - effect: NoSchedule
          key: node.ocs.openshift.io/storage
          value: 'true'
      providerSpec:
        value:
          userDataSecret:
            name: worker-user-data
          placement:
            availabilityZone: us-east-2b
            region: us-east-2
          credentialsSecret:
            name: aws-cloud-credentials
          instanceType: m5.4xlarge
          metadata:
            creationTimestamp: null
          blockDevices:
            - ebs:
                encrypted: true
                iops: 0
                kmsKey:
                  arn: ''
                volumeSize: 120
                volumeType: gp2
          securityGroups:
            - filters:
                - name: 'tag:Name'
                  values:
                    - cluster-24f2-xltdt-worker-sg
          kind: AWSMachineProviderConfig
          tags:
            - name: kubernetes.io/cluster/cluster-24f2-xltdt
              value: owned
            - name: guid
              value: 24f2
            - name: owner
              value: swilson@redhat.com
            - name: platform
              value: Red_Hat_OPENTLC
            - name: uuid
              value: 71f20388-3f55-45c8-8983-c78a883d3ffa
            - name: Stack
              value: project ocp4-cluster-24f2
            - name: catalog_item
              value: OCS_4_Implementation_on_AWS
            - name: email
              value: swilson@redhat.com
            - name: env_type
              value: ocp4-cluster
          deviceIndex: 0
          ami:
            id: ami-0c84b5c5255ec4777
          subnet:
            filters:
              - name: 'tag:Name'
                values:
                  - cluster-24f2-xltdt-private-us-east-2b
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          iamInstanceProfile:
            id: cluster-24f2-xltdt-worker-profile
